### ISSUE TITLE
Is this repo a fork of https://github.com/cold-hand/ComfyUI-FlashFace?

### ISSUE THREAD

**Issue by 2snEM6** [nuanarchy/ComfyUI-NuA-FlashFace#4]
Just by taking a look at the commits, is this repo a fork of [https://github.com/cold-hand/ComfyUI-FlashFace](https://github.com/cold-hand/ComfyUI-FlashFace)? I am asking because I'd like to know what the differences between each repos are.

Thank you for the good work 💪

**Comment by nuanarchy** [comment]
Hi @2snEM6 and thank you.
It's just another implementation of the original FlashFace, not a fork.

When I was working on the personalization task, I didn't find any other nodes for FlashFace, so I decided to make my own and share it with others.
Here the FlashFace code was slightly reworked and the node was added to various services for ease of use - ComfyUI Manager, Comfy Registry

**Comment by 2snEM6** [comment]
Thank you  for your answer @nuanarchy , I could install it using the manager, however, I am facing a super weird error, I tried to debug it but no luck. Here the issue: #5 . I will close this one then, thank you.
